### ISSUE TITLE
return more info than just bool

### ISSUE THREAD

**Issue by benoitjadinon** [aritchie/biometrics#3]
Hi, thanks for the library.

I've used it on iOS and planning to use it on Android in a couple of weeks, but found out to be quite restricted by the boolean return and dismissing of NSErrors.
So I'm thinking of forking and changing returns from bool to maybe an enum or something, I'm trying to find common patterns between platforms here : https://docs.google.com/spreadsheets/d/1iT35KqyuRWEMWQ8T7_c3lHxnU72dFvdEiF2IDTTTpY0/edit?usp=sharing

I was thinking something in the lines of :

```csharp
async BiometricsAvailability IsAvailable(){
    //...
}

async BiometricsEvaluationResult Evaluate(){
    var availability = await IsAvailable();
    if (availability != BiometricsAvailability.Available)
        throw new BiometricsAvailabilityException(availability);
    // await Evaluate here
}
```

what do you think @aritchie ?

**Comment by benoitjadinon** [comment]
I'll test #2 in the mean time, cause I'll need it

**Comment by benoitjadinon** [comment]
well, it's just what [xamarin-fingerprint](https://github.com/smstuebe/xamarin-fingerprint) is doing...

**Comment by aritchie** [comment]
Hi @benoitjadinon 
I appreciate the updates, but you are probably better to go with the plugin you just found since it is maintained.  This served my immediate needs a year ago and I haven't touched it since.

**Comment by benoitjadinon** [comment]
yup, may I suggest adding something like "obsolete" "not maintained" to this repo README ? 
I wouldn't have used it in production and would have searched for an alternative instead, thx
